// lib/export/budget-pdf.ts
// Printable budget (or combined Pay + Budget) PDF, drawn with pdf-lib using the
// Standard-14 Helvetica fonts. Runs in the browser so nothing leaves the device.

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";
import { formatUsd } from "./summary";
import { glossaryFor } from "./glossary";
import type { BudgetExport, BudgetLine } from "./budget-summary";

const PAGE_W = 612; // US Letter
const PAGE_H = 792;
const M = 50;
const RIGHT = PAGE_W - M;

const INK = rgb(0.11, 0.13, 0.16);
const MUTED = rgb(0.45, 0.48, 0.53);
const LINE = rgb(0.85, 0.87, 0.9);
const NAVY = rgb(0.07, 0.13, 0.29);
const ACCENT = rgb(0.05, 0.42, 0.38);
const NEGATIVE = rgb(0.72, 0.11, 0.11);
const TINT = rgb(0.965, 0.975, 0.985);
const WHITE = rgb(1, 1, 1);
const SUBTLE_WHITE = rgb(0.76, 0.81, 0.89);

const MONTHLY_RIGHT = 408;

type Fonts = { reg: PDFFont; bold: PDFFont };
type Rgb = ReturnType<typeof rgb>;

function rightText(page: PDFPage, text: string, rx: number, y: number, size: number, font: PDFFont, color: Rgb = INK) {
  page.drawText(text, { x: rx - font.widthOfTextAtSize(text, size), y, size, font, color });
}

function footer(page: PDFPage, f: Fonts) {
  page.drawLine({ start: { x: M, y: 78 }, end: { x: RIGHT, y: 78 }, thickness: 0.5, color: LINE });
  page.drawText("Planning estimate only - the numbers are whatever you entered.", {
    x: M, y: 64, size: 8, font: f.reg, color: MUTED,
  });
  page.drawText("Verify pay figures against your LES / myPay. Generated by ActivePayOS - activepayos.com", {
    x: M, y: 53, size: 8, font: f.reg, color: MUTED,
  });
}

export async function generateBudgetPdf(
  b: BudgetExport,
  chartPng?: Uint8Array
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("ActivePayOS Budget Summary");
  doc.setCreator("ActivePayOS");
  doc.setProducer("ActivePayOS");

  const f: Fonts = {
    reg: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
  };
  const chart = chartPng && chartPng.length > 0 ? await doc.embedPng(chartPng) : undefined;

  let page = doc.addPage([PAGE_W, PAGE_H]);
  const pages: PDFPage[] = [page];

  // ---- header band ----
  const bandH = b.pay ? 100 : 84;
  page.drawRectangle({ x: 0, y: PAGE_H - bandH, width: PAGE_W, height: bandH, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_H - bandH, width: PAGE_W, height: 5, color: ACCENT });
  page.drawText("ActivePayOS", { x: M, y: PAGE_H - 50, size: 24, font: f.bold, color: WHITE });
  page.drawText(b.pay ? "Pay + Budget Summary" : "Budget Summary", {
    x: M, y: PAGE_H - 70, size: 12, font: f.reg, color: SUBTLE_WHITE,
  });
  rightText(page, `Generated ${b.generatedOn}`, RIGHT, PAGE_H - 50, 9, f.reg, SUBTLE_WHITE);
  if (b.pay) {
    rightText(page, `${b.pay.grade}  -  ${b.pay.year}`, RIGHT, PAGE_H - 68, 13, f.bold, WHITE);
    rightText(page, `${b.pay.location}  -  ${b.pay.yosLabel}`, RIGHT, PAGE_H - 84, 9, f.reg, SUBTLE_WHITE);
  }

  let y = PAGE_H - bandH - 34;

  const ensureSpace = (needed: number) => {
    if (y - needed < 96) {
      footer(page, f);
      page = doc.addPage([PAGE_W, PAGE_H]);
      pages.push(page);
      y = PAGE_H - 60;
    }
  };

  const drawTable = (title: string, rows: BudgetLine[], total: BudgetLine, totalColor: Rgb = INK) => {
    ensureSpace(40);
    page.drawText(title.toUpperCase(), { x: M, y, size: 9, font: f.bold, color: MUTED });
    rightText(page, "MONTHLY", MONTHLY_RIGHT, y, 8, f.bold, MUTED);
    rightText(page, "ANNUAL", RIGHT, y, 8, f.bold, MUTED);
    y -= 6;
    page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
    y -= 20;

    rows.forEach((l, i) => {
      // A plain-English note (from the site's i-dot copy) adds a muted second
      // line, so the row grows when there is something worth explaining.
      const note = glossaryFor(l.label);
      const rowH = note ? 34 : 24;
      ensureSpace(rowH);
      if (i % 2 === 1) {
        page.drawRectangle({ x: M, y: y - (rowH - 18), width: RIGHT - M, height: rowH, color: TINT });
      }
      page.drawText(l.label, { x: M + 8, y, size: 11, font: f.reg, color: INK });
      rightText(page, formatUsd(l.monthly), MONTHLY_RIGHT, y, 11, f.reg, INK);
      rightText(page, formatUsd(l.monthly * 12), RIGHT, y, 11, f.reg, INK);
      if (note) {
        page.drawText(note, { x: M + 8, y: y - 10, size: 7, font: f.reg, color: MUTED, maxWidth: RIGHT - M - 16 });
      }
      y -= rowH;
    });

    ensureSpace(26);
    page.drawLine({ start: { x: M, y: y + 14 }, end: { x: RIGHT, y: y + 14 }, thickness: 1.2, color: INK });
    page.drawText(total.label, { x: M + 8, y, size: 12, font: f.bold, color: totalColor });
    rightText(page, formatUsd(total.monthly), MONTHLY_RIGHT, y, 12, f.bold, totalColor);
    rightText(page, formatUsd(total.monthly * 12), RIGHT, y, 12, f.bold, totalColor);
    y -= 34;
  };

  // ---- leftover box (the headline) — drawn FIRST, before any tables ----
  ensureSpace(58);
  const boxH = 50;
  const boxY = y - boxH + 10;
  const over = b.leftover < 0;
  page.drawRectangle({ x: M, y: boxY, width: RIGHT - M, height: boxH, color: TINT });
  page.drawRectangle({ x: M, y: boxY, width: 6, height: boxH, color: over ? NEGATIVE : ACCENT });
  page.drawText(over ? "OVERSPENT" : "LEFTOVER (INCOME - EXPENSES)", {
    x: M + 20, y: boxY + boxH - 20, size: 9, font: f.bold, color: MUTED,
  });
  page.drawText(`${formatUsd(Math.abs(b.leftover))} /mo`, {
    x: M + 20, y: boxY + 12, size: 20, font: f.bold, color: over ? NEGATIVE : ACCENT,
  });
  rightText(page, `${formatUsd(Math.abs(b.leftover) * 12)} /yr`, RIGHT - 20, boxY + 14, 13, f.bold, INK);
  y = boxY - 16;

  // One-line supporting stats under the box, then the detail tables.
  page.drawText(
    `Total income ${formatUsd(b.totalIncome)}/mo   -   Total expenses ${formatUsd(b.totalExpense)}/mo`,
    { x: M, y, size: 9, font: f.reg, color: MUTED }
  );
  y -= 26;

  // ---- optional pay lines (combined report) ----
  if (b.pay) {
    drawTable("Pay components", b.pay.lines, b.pay.total);
  }

  // ---- budget ----
  drawTable("Income", b.income, { label: "Total income", monthly: b.totalIncome });
  drawTable("Expenses", b.expenses, { label: "Total expenses", monthly: b.totalExpense });

  // ---- optional money-flow chart ----
  if (chart && chart.width > 0 && chart.height > 0) {
    ensureSpace(150);
    page.drawText("MONEY FLOW", { x: M, y, size: 8, font: f.bold, color: MUTED });
    const top = y - 10;
    const maxW = RIGHT - M;
    let w = maxW;
    let h = (chart.height / chart.width) * w;
    const availH = top - 96;
    if (h > availH) {
      h = availH;
      w = (chart.width / chart.height) * h;
    }
    page.drawImage(chart, { x: M + (maxW - w) / 2, y: top - h, width: w, height: h });
  }

  footer(page, f);
  return doc.save();
}
