// lib/export/pdf.ts
// PDF pay-summary generator, drawn with pdf-lib. Uses only the Standard-14
// Helvetica fonts (WinAnsi) so there are no font files to ship and it runs
// cleanly in the serverless Node runtime.
//
// One layout ships: "modern" — navy header band, highlighted total box first
// (summary up top), then a zebra-striped component table where each line
// carries a muted plain-English note from the export glossary. The old
// "classic" and "compact" layouts were unreachable from the UI and have been
// deleted.

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage, PDFImage } from "pdf-lib";
import { PaySummary, formatUsd } from "./summary";
import { glossaryFor } from "./glossary";

/** The single supported layout (kept as a named type for callers). */
export type PdfLayout = "modern";

const PAGE_W = 612; // US Letter
const PAGE_H = 792;

const INK = rgb(0.11, 0.13, 0.16);
const MUTED = rgb(0.45, 0.48, 0.53);
const LINE = rgb(0.85, 0.87, 0.9);
const NAVY = rgb(0.07, 0.13, 0.29);
const ACCENT = rgb(0.05, 0.42, 0.38);
const TINT = rgb(0.965, 0.975, 0.985);
const WHITE = rgb(1, 1, 1);
const SUBTLE_WHITE = rgb(0.76, 0.81, 0.89);

const DISCLAIMER_1 =
  "Not an official Department of War / Department of Defense (DoD), DFAS, or U.S. military document. For education and planning only.";
const DISCLAIMER_2 =
  "Verify against your LES / myPay. Generated by ActivePayOS - activepayos.com";

type Fonts = { reg: PDFFont; bold: PDFFont };
type Rgb = ReturnType<typeof rgb>;

function rightText(
  page: PDFPage,
  text: string,
  rightX: number,
  y: number,
  size: number,
  font: PDFFont,
  color: Rgb = INK
) {
  const w = font.widthOfTextAtSize(text, size);
  page.drawText(text, { x: rightX - w, y, size, font, color });
}

// ----------------------------------------------------------------- modern ---

function drawModern(page: PDFPage, f: Fonts, s: PaySummary, chart?: PDFImage) {
  const M = 50;
  const right = PAGE_W - M;
  const bandH = 120;

  page.drawRectangle({ x: 0, y: PAGE_H - bandH, width: PAGE_W, height: bandH, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_H - bandH, width: PAGE_W, height: 5, color: ACCENT });
  page.drawText("ActivePayOS", { x: M, y: PAGE_H - 56, size: 26, font: f.bold, color: WHITE });
  page.drawText("Pay Summary", { x: M, y: PAGE_H - 78, size: 12, font: f.reg, color: SUBTLE_WHITE });
  rightText(page, `${s.grade}  -  ${s.year}`, right, PAGE_H - 54, 13, f.bold, WHITE);
  rightText(page, `Generated ${s.generatedOn}`, right, PAGE_H - 72, 9, f.reg, SUBTLE_WHITE);

  const ctx: [string, string][] = [
    ["YEARS OF SERVICE", s.yosLabel],
    ["DUTY LOCATION", s.location],
    ["DEPENDENTS", s.dependents ? "Yes" : "No"],
    ["STATE OF LEGAL RESIDENCE", s.stateOfLegalResidence],
  ];
  const cXs = [M, 320];
  const cYs = [PAGE_H - bandH - 32, PAGE_H - bandH - 72];
  ctx.forEach((p, i) => {
    const x = cXs[i % 2];
    const yy = cYs[Math.floor(i / 2)];
    page.drawText(p[0], { x, y: yy, size: 8, font: f.bold, color: MUTED });
    page.drawText(p[1], { x, y: yy - 14, size: 12, font: f.reg, color: INK });
  });

  // Highlighted total box — the summary stays first.
  const boxTop = PAGE_H - bandH - 110;
  const boxH = 66;
  const boxY = boxTop - boxH;
  page.drawRectangle({ x: M, y: boxY, width: right - M, height: boxH, color: TINT });
  page.drawRectangle({ x: M, y: boxY, width: 6, height: boxH, color: ACCENT });
  page.drawText("TOTAL MONTHLY PAY", { x: M + 20, y: boxY + boxH - 22, size: 9, font: f.bold, color: MUTED });
  page.drawText(formatUsd(s.total.monthly), { x: M + 20, y: boxY + 16, size: 26, font: f.bold, color: ACCENT });
  rightText(page, "ANNUAL", right - 20, boxY + boxH - 22, 9, f.bold, MUTED);
  rightText(page, formatUsd(s.total.annual), right - 20, boxY + 18, 15, f.bold, INK);

  // Zebra table. Rows grow to fit a muted plain-English note (from the site's
  // i-dot popover copy) under each component label.
  const labelX = M + 12;
  const monthlyRight = 408;
  const annualRight = right - 12;
  let ty = boxY - 34;
  page.drawText("PAY COMPONENT", { x: labelX, y: ty, size: 8, font: f.bold, color: MUTED });
  rightText(page, "MONTHLY", monthlyRight, ty, 8, f.bold, MUTED);
  rightText(page, "ANNUAL", annualRight, ty, 8, f.bold, MUTED);
  ty -= 6;
  page.drawLine({ start: { x: M, y: ty }, end: { x: right, y: ty }, thickness: 1, color: LINE });

  let rowTop = ty;
  s.lines.forEach((l, i) => {
    const note = glossaryFor(l.label);
    const rowH = note ? 38 : 28;
    if (i % 2 === 1) {
      page.drawRectangle({ x: M, y: rowTop - rowH, width: right - M, height: rowH, color: TINT });
    }
    const baseline = rowTop - 19;
    page.drawText(l.label, { x: labelX, y: baseline, size: 11, font: f.reg, color: INK });
    rightText(page, formatUsd(l.monthly), monthlyRight, baseline, 11, f.reg, INK);
    rightText(page, formatUsd(l.annual), annualRight, baseline, 11, f.reg, INK);
    if (note) {
      page.drawText(note, {
        x: labelX,
        y: rowTop - 31,
        size: 7,
        font: f.reg,
        color: MUTED,
        maxWidth: right - M - 24,
      });
    }
    rowTop -= rowH;
  });

  const totalY = rowTop - 22;
  page.drawLine({ start: { x: M, y: totalY + 16 }, end: { x: right, y: totalY + 16 }, thickness: 1.2, color: INK });
  page.drawText(s.total.label, { x: labelX, y: totalY, size: 12, font: f.bold, color: INK });
  rightText(page, formatUsd(s.total.monthly), monthlyRight, totalY, 12, f.bold, INK);
  rightText(page, formatUsd(s.total.annual), annualRight, totalY, 12, f.bold, INK);

  // Optional pay-flow chart, scaled to fit the space above the footer.
  if (chart && chart.width > 0 && chart.height > 0) {
    const captionY = totalY - 28;
    page.drawText("WHERE YOUR PAY GOES", { x: M, y: captionY, size: 8, font: f.bold, color: MUTED });
    const top = captionY - 10;
    const minY = 92; // keep clear of the footer at y=78
    const maxW = right - M;
    let w = maxW;
    let h = (chart.height / chart.width) * w;
    const availH = top - minY;
    if (h > availH) {
      h = availH;
      w = (chart.width / chart.height) * h;
    }
    page.drawImage(chart, { x: M + (maxW - w) / 2, y: top - h, width: w, height: h });
  }

  footer(page, f);
}

// ------------------------------------------------------------------ shared ---

function footer(page: PDFPage, f: Fonts) {
  const M = 50;
  const right = PAGE_W - M;
  page.drawLine({ start: { x: M, y: 78 }, end: { x: right, y: 78 }, thickness: 0.5, color: LINE });
  page.drawText(DISCLAIMER_1, { x: M, y: 64, size: 8, font: f.reg, color: MUTED });
  page.drawText(DISCLAIMER_2, { x: M, y: 53, size: 8, font: f.reg, color: MUTED });
}

export async function generatePayPdf(
  summary: PaySummary,
  layout: PdfLayout = "modern",
  chartPng?: Uint8Array
): Promise<Uint8Array> {
  void layout; // single layout; parameter kept so existing call sites compile
  const doc = await PDFDocument.create();
  doc.setTitle(`ActivePayOS Pay Summary - ${summary.grade} ${summary.year}`);
  doc.setCreator("ActivePayOS");
  doc.setProducer("ActivePayOS");

  const page = doc.addPage([PAGE_W, PAGE_H]);
  const f: Fonts = {
    reg: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
  };

  const chart = chartPng && chartPng.length > 0 ? await doc.embedPng(chartPng) : undefined;

  drawModern(page, f, summary, chart);

  return doc.save();
}
