// lib/export/projection-pdf.ts
// Printable Wealth Projection PDF, drawn with pdf-lib (Standard-14 Helvetica).
// Runs in the browser so nothing leaves the device. Mirrors budget-pdf.ts.

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";
import { formatUsd } from "./summary";
import type { ProjectionExport } from "./projection";

const PAGE_W = 612; // US Letter
const PAGE_H = 792;
const M = 50;
const RIGHT = PAGE_W - M;

const INK = rgb(0.11, 0.13, 0.16);
const MUTED = rgb(0.45, 0.48, 0.53);
const LINE = rgb(0.85, 0.87, 0.9);
const NAVY = rgb(0.07, 0.13, 0.29);
const ACCENT = rgb(0.05, 0.42, 0.38);
const TINT = rgb(0.965, 0.975, 0.985);
const WHITE = rgb(1, 1, 1);
const SUBTLE_WHITE = rgb(0.76, 0.81, 0.89);

type Fonts = { reg: PDFFont; bold: PDFFont };
type Rgb = ReturnType<typeof rgb>;

function rightText(
  page: PDFPage,
  text: string,
  rx: number,
  y: number,
  size: number,
  font: PDFFont,
  color: Rgb = INK
) {
  page.drawText(text, { x: rx - font.widthOfTextAtSize(text, size), y, size, font, color });
}

function footer(page: PDFPage, f: Fonts) {
  page.drawLine({ start: { x: M, y: 78 }, end: { x: RIGHT, y: 78 }, thickness: 0.5, color: LINE });
  page.drawText("Planning estimate only - assumed returns are not guarantees; markets vary year to year.", {
    x: M, y: 64, size: 8, font: f.reg, color: MUTED,
  });
  page.drawText("Verify data at tsp.gov and DFAS. Generated by ActivePayOS - activepayos.com", {
    x: M, y: 53, size: 8, font: f.reg, color: MUTED,
  });
}

export async function generateProjectionPdf(
  p: ProjectionExport,
  chartPng?: Uint8Array
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("ActivePayOS Wealth Projection");
  doc.setCreator("ActivePayOS");
  doc.setProducer("ActivePayOS");

  const f: Fonts = {
    reg: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
  };
  const chart = chartPng && chartPng.length > 0 ? await doc.embedPng(chartPng) : undefined;
  const s = p.scenario;

  let page = doc.addPage([PAGE_W, PAGE_H]);

  // ---- header band ----
  page.drawRectangle({ x: 0, y: PAGE_H - 100, width: PAGE_W, height: 100, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_H - 100, width: PAGE_W, height: 5, color: ACCENT });
  page.drawText("ActivePayOS", { x: M, y: PAGE_H - 50, size: 24, font: f.bold, color: WHITE });
  page.drawText("Wealth Projection", { x: M, y: PAGE_H - 70, size: 12, font: f.reg, color: SUBTLE_WHITE });
  rightText(page, `Generated ${p.generatedOn}`, RIGHT, PAGE_H - 50, 9, f.reg, SUBTLE_WHITE);
  rightText(page, `${s.branchLabel}  ${s.grade}  -  ${s.yos} YOS`, RIGHT, PAGE_H - 68, 13, f.bold, WHITE);
  rightText(
    page,
    `${s.serviceYears} more years  -  through ${s.endYear} (age ${s.currentAge + s.projectionYears})`,
    RIGHT, PAGE_H - 84, 9, f.reg, SUBTLE_WHITE
  );

  let y = PAGE_H - 100 - 30;

  const ensureSpace = (needed: number) => {
    if (y - needed < 96) {
      footer(page, f);
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - 60;
    }
  };

  // ---- headline stats ----
  const stats: Array<[string, string]> = [
    [`Projected total (${s.endYear})`, formatUsd(p.totals.final)],
    ["In today's dollars", formatUsd(p.totals.finalReal)],
    ...(p.totals.atSeparation !== null && p.totals.separationYear !== null
      ? ([[`At separation (${p.totals.separationYear})`, formatUsd(p.totals.atSeparation)]] as Array<
          [string, string]
        >)
      : []),
    ["BRS agency match received", formatUsd(p.totals.agencyMatch)],
  ];
  const statW = (RIGHT - M) / stats.length;
  stats.forEach(([label, value], i) => {
    const x = M + i * statW;
    page.drawText(label.toUpperCase(), { x, y, size: 7, font: f.bold, color: MUTED, maxWidth: statW - 8 });
    page.drawText(value, { x, y: y - 16, size: 14, font: f.bold, color: NAVY });
  });
  y -= 44;

  // ---- assumptions ----
  page.drawText("ASSUMPTIONS", { x: M, y, size: 9, font: f.bold, color: MUTED });
  y -= 6;
  page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
  y -= 16;
  const assumptions = [
    `TSP: ${Math.round(s.tspPct * 100)}% of base pay${s.brs ? " + BRS match (1% auto, up to 4% match)" : ""}, ${s.tspReturnPct}%/yr assumed return`,
    `Investments: ${s.invReturnPct}%/yr  -  Savings: ${s.savApyPct}% APY  -  Inflation: ${s.inflationPct}%/yr  -  Military pay raise: ${s.payRaisePct}%/yr`,
    s.modelPromotions
      ? `Typical ${s.branchLabel} promotions modeled${
          p.promotions.length > 0
            ? `: ${p.promotions.map((x) => `${x.grade} ${x.year}${x.competitive ? "*" : ""}`).join(", ")}  (* board-driven, not guaranteed)`
            : " (none fall inside the service window)"
        }`
      : "Promotions not modeled - pay stays at the current grade (YOS raises still apply)",
  ];
  for (const a of assumptions) {
    page.drawText(a, { x: M, y, size: 9, font: f.reg, color: INK, maxWidth: RIGHT - M });
    y -= 14;
  }
  y -= 8;

  // ---- chart ----
  if (chart) {
    const cw = RIGHT - M;
    const ch = (chart.height / chart.width) * cw;
    ensureSpace(ch + 16);
    page.drawImage(chart, { x: M, y: y - ch, width: cw, height: ch });
    y -= ch + 20;
  }

  // ---- year table ----
  ensureSpace(48);
  page.drawText("YEAR BY YEAR", { x: M, y, size: 9, font: f.bold, color: MUTED });
  const C = { age: M + 44, grade: M + 78, tsp: 268, invest: 342, sav: 412, total: 486, real: RIGHT };
  rightText(page, "TSP", C.tsp, y, 8, f.bold, MUTED);
  rightText(page, "INVEST", C.invest, y, 8, f.bold, MUTED);
  rightText(page, "SAVINGS", C.sav, y, 8, f.bold, MUTED);
  rightText(page, "TOTAL", C.total, y, 8, f.bold, MUTED);
  rightText(page, "TODAY'S $", C.real, y, 8, f.bold, MUTED);
  y -= 6;
  page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
  y -= 16;

  const rowH = 17;
  p.years.forEach((yLine, i) => {
    ensureSpace(rowH + 8);
    const sepRow = p.totals.separationYear !== null && yLine.year === p.totals.separationYear;
    if (sepRow) {
      page.drawRectangle({ x: M, y: y - 4, width: RIGHT - M, height: rowH, color: TINT });
    } else if (i % 2 === 1) {
      page.drawRectangle({ x: M, y: y - 4, width: RIGHT - M, height: rowH, color: TINT });
    }
    const font = sepRow || i === p.years.length - 1 ? f.bold : f.reg;
    page.drawText(String(yLine.year) + (sepRow ? "*" : ""), { x: M + 4, y, size: 9, font, color: INK });
    page.drawText(String(yLine.age), { x: C.age, y, size: 9, font, color: INK });
    page.drawText(yLine.serving ? yLine.grade : "-", { x: C.grade, y, size: 9, font, color: INK });
    rightText(page, formatUsd(yLine.tsp), C.tsp, y, 9, font);
    rightText(page, formatUsd(yLine.invest), C.invest, y, 9, font);
    rightText(page, formatUsd(yLine.savings), C.sav, y, 9, font);
    rightText(page, formatUsd(yLine.total), C.total, y, 9, font);
    rightText(page, formatUsd(yLine.realTotal), C.real, y, 9, font, MUTED);
    y -= rowH;
  });
  if (p.totals.separationYear !== null) {
    ensureSpace(14);
    page.drawText("* separation year", { x: M, y, size: 8, font: f.reg, color: MUTED });
    y -= 14;
  }

  footer(page, f);
  return doc.save();
}
