// lib/export/projection-pdf.ts
// Printable Wealth Projection PDF, drawn with pdf-lib (Standard-14 Helvetica).
// Runs in the browser so nothing leaves the device. Mirrors budget-pdf.ts.

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";
import { formatUsd } from "./summary";
import { activeExtraAccounts, type ProjectionExport } from "./projection";

const PAGE_W = 612; // US Letter
const PAGE_H = 792;
const M = 50;
const RIGHT = PAGE_W - M;

const INK = rgb(0.11, 0.13, 0.16);
const MUTED = rgb(0.45, 0.48, 0.53);
const LINE = rgb(0.85, 0.87, 0.9);
const NAVY = rgb(0.07, 0.13, 0.29);
const ACCENT = rgb(0.05, 0.42, 0.38);
const TINT = rgb(0.965, 0.975, 0.985);
const WHITE = rgb(1, 1, 1);
const SUBTLE_WHITE = rgb(0.76, 0.81, 0.89);

type Fonts = { reg: PDFFont; bold: PDFFont };
type Rgb = ReturnType<typeof rgb>;

function rightText(
  page: PDFPage,
  text: string,
  rx: number,
  y: number,
  size: number,
  font: PDFFont,
  color: Rgb = INK
) {
  page.drawText(text, { x: rx - font.widthOfTextAtSize(text, size), y, size, font, color });
}

function footer(page: PDFPage, f: Fonts) {
  page.drawLine({ start: { x: M, y: 78 }, end: { x: RIGHT, y: 78 }, thickness: 0.5, color: LINE });
  page.drawText("Planning estimate only - assumed returns are not guarantees; markets vary year to year.", {
    x: M, y: 64, size: 8, font: f.reg, color: MUTED,
  });
  page.drawText("Verify data at tsp.gov and DFAS. Generated by ActivePayOS - activepayos.com", {
    x: M, y: 53, size: 8, font: f.reg, color: MUTED,
  });
}

export async function generateProjectionPdf(
  p: ProjectionExport,
  chartPng?: Uint8Array
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("ActivePayOS Wealth Projection");
  doc.setCreator("ActivePayOS");
  doc.setProducer("ActivePayOS");

  const f: Fonts = {
    reg: await doc.embedFont(StandardFonts.Helvetica),
    bold: await doc.embedFont(StandardFonts.HelveticaBold),
  };
  const chart = chartPng && chartPng.length > 0 ? await doc.embedPng(chartPng) : undefined;
  const s = p.scenario;

  let page = doc.addPage([PAGE_W, PAGE_H]);

  // ---- header band ----
  page.drawRectangle({ x: 0, y: PAGE_H - 100, width: PAGE_W, height: 100, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_H - 100, width: PAGE_W, height: 5, color: ACCENT });
  page.drawText("ActivePayOS", { x: M, y: PAGE_H - 50, size: 24, font: f.bold, color: WHITE });
  page.drawText("Wealth Projection", { x: M, y: PAGE_H - 70, size: 12, font: f.reg, color: SUBTLE_WHITE });
  rightText(page, `Generated ${p.generatedOn}`, RIGHT, PAGE_H - 50, 9, f.reg, SUBTLE_WHITE);
  rightText(page, `${s.branchLabel}  ${s.grade}  -  ${s.yos} YOS`, RIGHT, PAGE_H - 68, 13, f.bold, WHITE);
  rightText(
    page,
    `${s.serviceYears} more years  -  through ${s.endYear} (age ${s.currentAge + s.projectionYears})`,
    RIGHT, PAGE_H - 84, 9, f.reg, SUBTLE_WHITE
  );

  let y = PAGE_H - 100 - 30;

  const ensureSpace = (needed: number) => {
    if (y - needed < 96) {
      footer(page, f);
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - 60;
    }
  };

  // ---- headline stats ----
  const stats: Array<[string, string]> = [
    [`Projected total (${s.endYear})`, formatUsd(p.totals.final)],
    ["In today's dollars", formatUsd(p.totals.finalReal)],
    ...(p.totals.atSeparation !== null && p.totals.separationYear !== null
      ? ([[`At separation (${p.totals.separationYear})`, formatUsd(p.totals.atSeparation)]] as Array<
          [string, string]
        >)
      : []),
    ["BRS agency match received", formatUsd(p.totals.agencyMatch)],
  ];
  const statW = (RIGHT - M) / stats.length;
  stats.forEach(([label, value], i) => {
    const x = M + i * statW;
    page.drawText(label.toUpperCase(), { x, y, size: 7, font: f.bold, color: MUTED, maxWidth: statW - 8 });
    page.drawText(value, { x, y: y - 16, size: 14, font: f.bold, color: NAVY });
  });
  y -= 44;

  // ---- assumptions ----
  page.drawText("ASSUMPTIONS", { x: M, y, size: 9, font: f.bold, color: MUTED });
  y -= 6;
  page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
  y -= 16;
  const assumptions = [
    `TSP: ${Math.round(s.tspPct * 100)}% of base pay${s.brs ? " + BRS match (1% auto, up to 4% match)" : ""}, ${s.tspReturnPct}%/yr assumed return`,
    `Investments: ${s.invReturnPct}%/yr  -  Savings: ${s.savApyPct}% APY  -  Inflation: ${s.inflationPct}%/yr  -  Military pay raise: ${s.payRaisePct}%/yr`,
    ...(s.iraMonthly && s.iraMonthly > 0
      ? [
          `Civilian IRA: ${formatUsd(s.iraMonthly)}/mo until age ${s.iraUntilAge ?? "-"}, ${s.iraReturnPct ?? "-"}%/yr net of fees`,
        ]
      : []),
    ...(s.k401Monthly && s.k401Monthly > 0
      ? [
          `Civilian 401(k) after service: ${formatUsd(s.k401Monthly)}/mo (incl. employer match) until age ${s.k401UntilAge ?? "-"}, ${s.k401ReturnPct ?? "-"}%/yr`,
        ]
      : []),
    s.modelPromotions
      ? `Typical ${s.branchLabel} promotions modeled${
          p.promotions.length > 0
            ? `: ${p.promotions.map((x) => `${x.grade} ${x.year}${x.competitive ? "*" : ""}`).join(", ")}  (* board-driven, not guaranteed)`
            : " (none fall inside the service window)"
        }`
      : "Promotions not modeled - pay stays at the current grade (YOS raises still apply)",
  ];
  for (const a of assumptions) {
    page.drawText(a, { x: M, y, size: 9, font: f.reg, color: INK, maxWidth: RIGHT - M });
    y -= 14;
  }
  y -= 8;

  // ---- chart ----
  if (chart) {
    const cw = RIGHT - M;
    const ch = (chart.height / chart.width) * cw;
    ensureSpace(ch + 16);
    page.drawImage(chart, { x: M, y: y - ch, width: cw, height: ch });
    y -= ch + 20;
  }

  // ---- year table ----
  ensureSpace(48);
  page.drawText("YEAR BY YEAR", { x: M, y, size: 9, font: f.bold, color: MUTED });
  const extras = activeExtraAccounts(p);
  // Numeric columns are laid out dynamically so IRA/401(k) appear only when used.
  const numericHeads: { key: "tsp" | "ira" | "k401" | "invest" | "savings" | "total" | "realTotal"; head: string }[] = [
    { key: "tsp", head: "TSP" },
    ...(extras.ira ? [{ key: "ira" as const, head: "IRA" }] : []),
    ...(extras.k401 ? [{ key: "k401" as const, head: "401(K)" }] : []),
    { key: "invest", head: "INVEST" },
    { key: "savings", head: "SAVINGS" },
    { key: "total", head: "TOTAL" },
    { key: "realTotal", head: "TODAY'S $" },
  ];
  const numLeft = M + 108;
  const colW = (RIGHT - numLeft) / numericHeads.length;
  const colRight = (idx: number) => numLeft + colW * (idx + 1);
  const tableFontSize = numericHeads.length > 5 ? 8 : 9;
  const gradeX = M + 74;
  numericHeads.forEach((c, idx) => rightText(page, c.head, colRight(idx), y, 7.5, f.bold, MUTED));
  y -= 6;
  page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
  y -= 16;

  const rowH = 17;
  p.years.forEach((yLine, i) => {
    ensureSpace(rowH + 8);
    const sepRow = p.totals.separationYear !== null && yLine.year === p.totals.separationYear;
    if (sepRow) {
      page.drawRectangle({ x: M, y: y - 4, width: RIGHT - M, height: rowH, color: TINT });
    } else if (i % 2 === 1) {
      page.drawRectangle({ x: M, y: y - 4, width: RIGHT - M, height: rowH, color: TINT });
    }
    const font = sepRow || i === p.years.length - 1 ? f.bold : f.reg;
    page.drawText(String(yLine.year) + (sepRow ? "*" : ""), { x: M + 4, y, size: tableFontSize, font, color: INK });
    page.drawText(String(yLine.age), { x: M + 42, y, size: tableFontSize, font, color: INK });
    page.drawText(yLine.serving ? yLine.grade : "-", { x: gradeX, y, size: tableFontSize, font, color: INK });
    numericHeads.forEach((c, idx) => {
      rightText(
        page,
        formatUsd(yLine[c.key]),
        colRight(idx),
        y,
        tableFontSize,
        font,
        c.key === "realTotal" ? MUTED : INK
      );
    });
    y -= rowH;
  });
  if (p.totals.separationYear !== null) {
    ensureSpace(14);
    page.drawText("* separation year", { x: M, y, size: 8, font: f.reg, color: MUTED });
    y -= 14;
  }

  // ---- optional sections: fees, Roth trade space, long-term analysis ----
  const sectionHead = (label: string) => {
    ensureSpace(40);
    y -= 8;
    page.drawText(label, { x: M, y, size: 9, font: f.bold, color: MUTED });
    y -= 6;
    page.drawLine({ start: { x: M, y }, end: { x: RIGHT, y }, thickness: 1, color: LINE });
    y -= 14;
  };
  const bodyLine = (text: string, bold = false, indent = 0) => {
    ensureSpace(14);
    page.drawText(text, {
      x: M + indent,
      y,
      size: 8.5,
      font: bold ? f.bold : f.reg,
      color: INK,
      maxWidth: RIGHT - M - indent,
      lineHeight: 10.5,
    });
    // Rough wrap allowance: bump extra for long lines.
    const linesUsed = Math.ceil(f.reg.widthOfTextAtSize(text, 8.5) / (RIGHT - M - indent));
    y -= 13 * Math.max(1, linesUsed);
  };

  if (p.fees) {
    sectionHead("FUND MANAGEMENT FEES");
    bodyLine(
      `TSP expense ratio: ${p.fees.tspExpenseRatioPct}%/yr (about $${(p.fees.tspExpenseRatioPct * 10).toFixed(2)} per $1,000 invested per year)` +
        (p.fees.iraExpenseRatioPct !== null ? `  -  IRA expense ratio: ${p.fees.iraExpenseRatioPct}%/yr` : ""),
      true
    );
    bodyLine(`Estimated dollars lost to fees over this horizon: ${formatUsd(p.fees.estimatedFeeDrag)}`, true);
    for (const n of p.fees.notes) bodyLine(`- ${n}`, false, 6);
  }

  if (p.rothTradeoff) {
    const r = p.rothTradeoff;
    sectionHead("ROTH VS TRADITIONAL TRADE SPACE");
    bodyLine(
      `${formatUsd(r.monthlyContribution)}/mo for ${r.yearsContributing} years, withdrawn after ${r.yearsToWithdrawal} years at ${r.annualReturnPct}%/yr  -  tax rate ${r.taxRateNowPct}% today vs ${r.taxRateAtWithdrawalPct}% at withdrawal`
    );
    bodyLine(`Pre-tax balance at horizon (identical both ways): ${formatUsd(r.preTaxBalance)}`);
    bodyLine(
      `Roth: pay ${formatUsd(r.taxPaidUpFront)} in tax up front, keep ${formatUsd(r.rothAfterTax)} tax-free at the horizon`
    );
    bodyLine(
      `Traditional: pay $0 up front, owe ${formatUsd(r.deferredTaxBill)} at withdrawal, keep ${formatUsd(r.tradAfterTax)}`
    );
    bodyLine(
      r.winner === "even"
        ? "Verdict: effectively even at these tax rates."
        : `Verdict: ${r.winner === "roth" ? "Roth" : "Traditional"} comes out ahead by about ${formatUsd(r.advantage)} (net of the up-front tax).`,
      true
    );
  }

  if (p.longTerm) {
    sectionHead("LONG-TERM ANALYSIS");
    for (const m of p.longTerm.milestones) {
      bodyLine(`Age ${m.age} (${m.year}):  ${formatUsd(m.total)}   (${formatUsd(m.realTotal)} in today's dollars)`);
    }
    bodyLine(
      `Sustainable withdrawal at ~4%/yr: ${formatUsd(p.longTerm.fourPercentAnnual)}/yr = ${formatUsd(p.longTerm.fourPercentMonthly)}/mo (${formatUsd(p.longTerm.fourPercentMonthlyReal)}/mo in today's dollars)`,
      true
    );
    for (const n of p.longTerm.notes) bodyLine(`- ${n}`, false, 6);
  }

  footer(page, f);
  return doc.save();
}
