// lib/export/projection.ts
// Wealth Projector exports (CSV / TXT). Pure string builders — generated
// entirely in the browser, mirroring lib/export/budget-summary.ts.

import { formatPlain, formatUsd } from "./summary";

export type ProjectionYearLine = {
  year: number;
  age: number;
  serving: boolean;
  grade: string;
  basePayMonthly: number;
  tsp: number;
  invest: number;
  savings: number;
  total: number;
  realTotal: number;
};

export type ProjectionExport = {
  generatedOn: string; // YYYY-MM-DD
  scenario: {
    branchLabel: string;
    track: string;
    grade: string;
    yos: number;
    currentAge: number;
    serviceYears: number;
    projectionYears: number;
    endYear: number;
    tspPct: number; // decimal
    brs: boolean;
    tspReturnPct: number;
    invReturnPct: number;
    savApyPct: number;
    inflationPct: number;
    payRaisePct: number;
    modelPromotions: boolean;
  };
  promotions: { year: number; grade: string; competitive: boolean }[];
  years: ProjectionYearLine[];
  totals: {
    final: number;
    finalReal: number;
    atSeparation: number | null;
    separationYear: number | null;
    contributed: number;
    growth: number;
    agencyMatch: number;
  };
};

// -------------------------------------------------------------------- CSV ---

function csvCell(value: string | number): string {
  let s = String(value);
  if (/^[=+\-@\t\r]/.test(s) && !/^[-+]?(?:\d+\.?\d*|\.\d+)$/.test(s)) {
    s = `'${s}`;
  }
  if (/[",\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function row(cells: Array<string | number>): string {
  return cells.map(csvCell).join(",");
}

export function generateProjectionCsv(p: ProjectionExport): string {
  const s = p.scenario;
  const lines: string[] = [];

  lines.push(row(["ActivePayOS Wealth Projection"]));
  lines.push(row(["Generated", p.generatedOn]));
  lines.push("");
  lines.push(row(["Scenario", ""]));
  lines.push(row(["Branch", s.branchLabel]));
  lines.push(row(["Track", s.track]));
  lines.push(row(["Current grade", s.grade]));
  lines.push(row(["Current years of service", s.yos]));
  lines.push(row(["Current age", s.currentAge]));
  lines.push(row(["Years staying in", s.serviceYears]));
  lines.push(row(["Projection horizon (years)", s.projectionYears]));
  lines.push(row(["Projected through", s.endYear]));
  lines.push(row(["TSP contribution (% of base pay)", s.tspPct * 100]));
  lines.push(row(["BRS agency contributions", s.brs ? "Yes" : "No"]));
  lines.push(row(["Assumed TSP return (%/yr)", s.tspReturnPct]));
  lines.push(row(["Assumed investment return (%/yr)", s.invReturnPct]));
  lines.push(row(["Savings APY (%)", s.savApyPct]));
  lines.push(row(["Inflation assumption (%/yr)", s.inflationPct]));
  lines.push(row(["Assumed annual military pay raise (%)", s.payRaisePct]));
  lines.push(row(["Typical promotions modeled", s.modelPromotions ? "Yes" : "No"]));

  if (p.promotions.length > 0) {
    lines.push("");
    lines.push(row(["Projected promotions", ""]));
    for (const promo of p.promotions) {
      lines.push(
        row([promo.grade, promo.year, promo.competitive ? "board/exam-driven (not guaranteed)" : "largely time-based"])
      );
    }
  }

  lines.push("");
  lines.push(
    row([
      "Year",
      "Age",
      "Serving",
      "Grade",
      "Base pay (monthly USD)",
      "TSP (USD)",
      "Investments (USD)",
      "Savings (USD)",
      "Total (USD)",
      "Total (today's USD)",
    ])
  );
  for (const yLine of p.years) {
    lines.push(
      row([
        yLine.year,
        yLine.age,
        yLine.serving ? "Yes" : "No",
        yLine.serving ? yLine.grade : "",
        yLine.serving ? formatPlain(yLine.basePayMonthly) : "",
        formatPlain(yLine.tsp),
        formatPlain(yLine.invest),
        formatPlain(yLine.savings),
        formatPlain(yLine.total),
        formatPlain(yLine.realTotal),
      ])
    );
  }

  lines.push("");
  lines.push(row(["Totals", ""]));
  if (p.totals.atSeparation !== null && p.totals.separationYear !== null) {
    lines.push(row([`At separation (${p.totals.separationYear})`, formatPlain(p.totals.atSeparation)]));
  }
  lines.push(row([`Projected total (${s.endYear})`, formatPlain(p.totals.final)]));
  lines.push(row(["In today's dollars", formatPlain(p.totals.finalReal)]));
  lines.push(row(["Total contributed (incl. starting balances)", formatPlain(p.totals.contributed)]));
  lines.push(row(["Market growth", formatPlain(p.totals.growth)]));
  lines.push(row(["BRS agency match received", formatPlain(p.totals.agencyMatch)]));
  lines.push("");
  lines.push(
    row([
      "Planning estimate only. Assumed returns are not guarantees; verify data at tsp.gov and DFAS. Generated by ActivePayOS - activepayos.com",
    ])
  );

  return lines.join("\r\n") + "\r\n";
}

// -------------------------------------------------------------------- TXT ---

export function generateProjectionTxt(p: ProjectionExport): string {
  const s = p.scenario;
  const w = 74;
  const div = "-".repeat(w);
  const kv = (label: string, value: string) => `${label.padEnd(44)}${value}`;
  const lines: string[] = [];

  lines.push("ACTIVEPAYOS WEALTH PROJECTION");
  lines.push(`Generated ${p.generatedOn}`);
  lines.push(div);
  lines.push(kv("Scenario", `${s.branchLabel} ${s.grade}, ${s.yos} YOS, age ${s.currentAge}`));
  lines.push(kv("Staying in", `${s.serviceYears} more year(s)`));
  lines.push(kv("Projected through", `${s.endYear} (age ${s.currentAge + s.projectionYears})`));
  lines.push(
    kv("TSP", `${Math.round(s.tspPct * 100)}% of base pay${s.brs ? " + BRS match" : ""} at ${s.tspReturnPct}%/yr`)
  );
  lines.push(kv("Investments / Savings returns", `${s.invReturnPct}%/yr / ${s.savApyPct}% APY`));
  lines.push(kv("Inflation / annual pay raise", `${s.inflationPct}% / ${s.payRaisePct}%`));
  if (p.promotions.length > 0) {
    lines.push(
      kv(
        "Projected promotions",
        p.promotions.map((x) => `${x.grade} ${x.year}${x.competitive ? "*" : ""}`).join(", ") +
          "   (* board-driven, not guaranteed)"
      )
    );
  }
  lines.push(div);
  lines.push(
    ["Year", "Age", "Grade", "TSP", "Invest", "Savings", "Total", "Today's $"]
      .map((h, i) => (i < 3 ? h.padEnd(i === 0 ? 6 : 5) : h.padStart(10)))
      .join("")
  );
  for (const yLine of p.years) {
    lines.push(
      [
        String(yLine.year).padEnd(6),
        String(yLine.age).padEnd(5),
        (yLine.serving ? yLine.grade : "-").padEnd(5),
        formatUsd(yLine.tsp).padStart(10),
        formatUsd(yLine.invest).padStart(10),
        formatUsd(yLine.savings).padStart(10),
        formatUsd(yLine.total).padStart(10),
        formatUsd(yLine.realTotal).padStart(10),
      ].join("")
    );
  }
  lines.push(div);
  if (p.totals.atSeparation !== null && p.totals.separationYear !== null) {
    lines.push(kv(`At separation (${p.totals.separationYear})`, formatUsd(p.totals.atSeparation)));
  }
  lines.push(kv(`Projected total (${s.endYear})`, formatUsd(p.totals.final)));
  lines.push(kv("In today's dollars", formatUsd(p.totals.finalReal)));
  lines.push(kv("Total contributed", formatUsd(p.totals.contributed)));
  lines.push(kv("Market growth", formatUsd(p.totals.growth)));
  lines.push(kv("BRS agency match received", formatUsd(p.totals.agencyMatch)));
  lines.push(div);
  lines.push("Planning estimate only. Assumed returns are not guarantees; markets vary");
  lines.push("year to year. Verify data at tsp.gov and DFAS.");
  lines.push("Generated by ActivePayOS - activepayos.com");

  return lines.join("\r\n") + "\r\n";
}
