// lib/export/timeline-txt.ts
// Human-readable plain-text timeline.

import { TimelineResult, TimelineInputs, EventKind } from "@/lib/promotion/timeline";
import { formatUsd } from "./summary";

const KIND_TAG: Record<EventKind, string> = {
  start: "[START]",
  promotion: "[PROMO]",
  "early-promotion": "[EARLY]",
  "gi-bill": "[GIBILL]",
  service: "[SVC]",
  retirement: "[RETIRE]",
  today: "[TODAY]",
};

export function generateTimelineTxt(
  result: TimelineResult,
  inputs: TimelineInputs,
  generatedOn: string
): string {
  const out: string[] = [];

  out.push("ActivePayOS - Career Milestone Planner");
  out.push("======================================");
  out.push("");

  const ctx: Array<[string, string]> = [
    ["Branch", result.branchLabel],
    ["Track", inputs.track === "officer" ? "Officer" : "Enlisted"],
    ["Start grade", result.startGrade],
    [inputs.track === "officer" ? "Date commissioned" : "Date entered service", inputs.accessionDate],
    ["Current obligation", `${inputs.contractYears} years`],
    ["20-year scenario final grade", result.finalGrade],
    ["Generated", generatedOn],
  ];
  const w = Math.max(...ctx.map(([k]) => k.length)) + 2;
  for (const [k, v] of ctx) {
    out.push(`${(k + ":").padEnd(w)} ${v}`);
  }

  out.push("");
  out.push("Timeline");
  out.push("--------");
  for (const e of result.events) {
    const tag = KIND_TAG[e.kind];
    const pay =
      e.monthlyBasePay != null ? `  -  ${formatUsd(e.monthlyBasePay)}/mo` : "";
    const delta =
      e.payDelta != null && e.payDelta !== 0
        ? ` (${e.payDelta > 0 ? "+" : ""}${formatUsd(e.payDelta)})`
        : "";
    const est = e.estimate ? " *" : "";
    out.push(`${e.dateISO}  ${tag}  ${e.title}${est}`);
    out.push(`            ${e.sinceStart} in${pay}${delta}`);
    if (e.detail) out.push(`            ${e.detail}`);
    out.push("");
  }

  out.push("* = planning estimate (board/exam-driven or rule-of-thumb timing).");
  out.push("");
  out.push(`Promotion timing source: ${result.source.label}`);
  out.push(`  ${result.source.url}`);
  out.push("");
  out.push("Not an official Department of War / Department of Defense (DoD), DFAS, VA, or branch promotion document.");
  out.push("Best for enlisted planning; officer mode is a broad commissioned-service sketch.");
  out.push("Actual dates depend on branch, career field, eligibility, PME, TIG/TIS, waivers,");
  out.push("manning, boards, performance, and policy changes. Verify with official sources.");
  out.push("Generated by ActivePayOS - https://activepayos.com");
  out.push("");

  return out.join("\n");
}
