// lib/export/txt.ts
// Plain-text pay summary: human-readable, aligned, opens in any editor.

import { PaySummary, formatUsd } from "./summary";

function padRight(s: string, width: number): string {
  return s.length >= width ? s : s + " ".repeat(width - s.length);
}
function padLeft(s: string, width: number): string {
  return s.length >= width ? s : " ".repeat(width - s.length) + s;
}

export function generatePayTxt(summary: PaySummary): string {
  const out: string[] = [];

  out.push("ActivePayOS - Pay Summary");
  out.push("=========================");
  out.push("");

  const context: Array<[string, string]> = [
    ["Year", String(summary.year)],
    ["Grade", summary.grade],
    ["Years of Service", summary.yosLabel],
    ["Location", summary.location],
    ["Dependents", summary.dependents ? "Yes" : "No"],
    ["State of Legal Residence", summary.stateOfLegalResidence],
    ["Generated", summary.generatedOn],
  ];
  const labelWidth = Math.max(...context.map(([k]) => k.length)) + 2;
  for (const [k, v] of context) {
    out.push(`${padRight(k + ":", labelWidth)} ${v}`);
  }

  out.push("");

  // Size each column to its widest cell so rows always line up.
  const allRows = [...summary.lines, summary.total];
  const monthlyStrs = allRows.map((l) => formatUsd(l.monthly));
  const annualStrs = allRows.map((l) => formatUsd(l.annual));
  const nameWidth = Math.max("Pay Component".length, ...allRows.map((l) => l.label.length)) + 2;
  const monthlyWidth = Math.max("Monthly".length, ...monthlyStrs.map((s) => s.length)) + 2;
  const annualWidth = Math.max("Annual".length, ...annualStrs.map((s) => s.length)) + 2;
  const ruleWidth = nameWidth + monthlyWidth + annualWidth;

  const tableRow = (name: string, monthly: string, annual: string) =>
    padRight(name, nameWidth) + padLeft(monthly, monthlyWidth) + padLeft(annual, annualWidth);

  out.push(tableRow("Pay Component", "Monthly", "Annual"));
  out.push("-".repeat(ruleWidth));
  summary.lines.forEach((l, i) => {
    out.push(tableRow(l.label, monthlyStrs[i], annualStrs[i]));
  });
  out.push("-".repeat(ruleWidth));
  out.push(
    tableRow(
      summary.total.label,
      monthlyStrs[monthlyStrs.length - 1],
      annualStrs[annualStrs.length - 1]
    )
  );

  out.push("");
  out.push("Not an official Department of War / Department of Defense (DoD), DFAS, or U.S. military document.");
  out.push("For education and planning only - verify against your LES / myPay.");
  out.push("Generated by ActivePayOS - https://activepayos.com");
  out.push("");

  return out.join("\n");
}
